# Generated by Django 3.2 on 2021-04-13 18:20

import datacollection.models
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to=datacollection.models.path_to_file)),
                ('username', models.CharField(max_length=128)),
            ],
        ),
    ]
